{{- if and .Values.running .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phraseanet-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phraseanet
      tier: rabbitmq
  template:
    metadata:
      labels:
        app: phraseanet
        tier: rabbitmq
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.rabbitmq.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.rabbitmq.persistence.existingClaim | default (printf "phraseanet-rabbitmq") }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "rabbitmq"
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: data
          mountPath: "/var/lib/rabbitmq"
        {{- if or .Values.rabbitmq.runAsUser .Values.rabbitmq.runAsGroup }}
        securityContext:
          {{- if .Values.rabbitmq.runAsUser }}
          runAsUser: {{ .Values.rabbitmq.runAsUser }}
          {{- end }}
          {{- if .Values.rabbitmq.runAsGroup }}
          runAsGroup: {{ .Values.rabbitmq.runAsGroup }}
          {{- end }}
        {{- end }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ tpl .Values.rabbitmq.default_user $ | quote }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ tpl .Values.rabbitmq.default_pass $ | quote }}
        - name: RABBITMQ_NODE_PORT
          value: {{ tpl .Values.rabbitmq.port $ | quote }}
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ tpl .Values.rabbitmq.default_vhost $ | quote }}
        - name: RABBITMQ_HEARTBEAT
          value: {{ .Values.rabbitmq.heartbeat | quote }}
        - name: RABBITMQ_NODENAME
          value: {{ tpl .Values.rabbitmq.node_name $ | quote }}
{{- end }}
