{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
  - name: rabbitmq-mgmt
    port: 15672
    targetPort: 15672
  selector:
    app: phraseanet
    tier: rabbitmq
{{- end }}
