{{- if .Values.running  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phraseanet-redis-session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phraseanet
      tier: redis-session
  template:
    metadata:
      labels:
        app: phraseanet
        tier: redis-session
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
      containers:
      - name: redis-session
        image: redis:5.0.5
        terminationMessagePolicy: FallbackToLogsOnError
{{- end }}