apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.datastores.yml convert --verbose --out ./kompose
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  containers:
    - env:
        - name: GATEWAY_ALLOWED_IPS
        - name: GATEWAY_CSP
        - name: GATEWAY_DENIED_IPS
        - name: GATEWAY_FASTCGI_HTTPS
          value: "off"
        - name: GATEWAY_FASTCGI_TIMEOUT
          value: "300"
        - name: GATEWAY_PROXY_TIMEOUT
          value: "120"
        - name: GATEWAY_SEND_TIMEOUT
          value: "120"
        - name: GATEWAY_STATUS_ALLOWED_IPS
        - name: GATEWAY_USERS
        - name: HTTP_READ_REQUEST_LIMIT_BURST
          value: "20"
        - name: HTTP_READ_REQUEST_LIMIT_MEMORY
          value: "10"
        - name: HTTP_READ_REQUEST_LIMIT_RATE
          value: "100"
        - name: HTTP_REQUEST_LIMITS
          value: "false"
        - name: HTTP_WRITE_REQUEST_LIMIT_BURST
          value: "20"
        - name: HTTP_WRITE_REQUEST_LIMIT_MEMORY
          value: "10"
        - name: HTTP_WRITE_REQUEST_LIMIT_RATE
          value: "100"
        - name: MAX_BODY_SIZE
          value: 1G
        - name: PHRASEANET_K8S_NAMESPACE
        - name: PHRASEANET_TRUSTED_PROXIES
      image: alchemyfr/phraseanet-nginx:4.1.15
      name: gateway
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/alchemy/Phraseanet/datas
          name: gateway-cm0
        - mountPath: /var/alchemy/Phraseanet/www/thumbnails
          name: gateway-cm1
        - mountPath: /var/alchemy/Phraseanet/www/custom
          name: gateway-cm2
        - mountPath: /var/alchemy/Phraseanet/www/plugins
          name: gateway-claim3
  restartPolicy: OnFailure
  volumes:
    - configMap:
        name: gateway-cm0
      name: gateway-cm0
    - configMap:
        name: gateway-cm1
      name: gateway-cm1
    - configMap:
        name: gateway-cm2
      name: gateway-cm2
    - name: gateway-claim3
      persistentVolumeClaim:
        claimName: gateway-claim3
