ingress:
  enabled: true
  host: phraseanet
  tls: false
  annotations:
    alb.ingress.kubernetes.io/ingress-class: "phraseanet-alb"
    alb.ingress.kubernetes.io/tags: "Name=phraseanet-alb,Owner=YourName,Project=mam-on-eks"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    # alb.ingress.kubernetes.io/success-codes: 200,201,302