running: true

image:
  registry: alchemyfr
  imagePullPolicy: IfNotPresent
  tag:
      phraseanet: 4.1.15
      phraseanet_saml_sp: latest
      database: 4.1.15
      elasticsearch: 4.1.15
  pullSecret:
    enabled: false
    name: registry-secret
    registry:
    username:
    password:
    email:

nodeSelector:
  
mysql:
  enabled: true
  user: "{{ .Values.app.phraseanet_db_user }}"
  password: "{{ .Values.app.phraseanet_db_password }}"
  root_password: "{{ .Values.app.phraseanet_db_password }}"
  max_allowed_packet: 16M
  max_connection: 100
  pvc_name: phraseanet-database
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  persistence:
    enabled: true
    existingClaim:
    storageClass: standard
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 1Gi

elasticsearch:
  enabled: true
  pvc_name: phraseanet-elasticsearch
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  persistence:
    enabled: true
    existingClaim:
    storageClass: standard
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 1Gi

rabbitmq:
  enabled: false
#   port: "{{ .Values.app.phraseanet_rabbitmq_port }}"
#   default_user: "{{ .Values.app.phraseanet_rabbitmq_user }}"
#   default_pass: "{{ .Values.app.phraseanet_rabbitmq_pass }}"
#   default_vhost: "{{ .Values.app.phraseanet_rabbitmq_vhost }}"
#   node_name: rabbit@rabbitmq
#   heartbeat: 60
#   runAsUser:
#   runAsGroup:
#   persistence:
#     enabled: true
#     existingClaim:
#     storageClass: standard
#     annotations: {}
#     accessMode: ReadWriteOnce
#     size: 1Gi
#   resources:
#     requests:
#       cpu: "50m"
#       memory: "256Mi"
#     limits:
#       cpu: "2000m"
#       memory: "4096Mi"

externalservice:
  pusher:
    pusher_auth_key:
    pusher_secret:
    pusher_app_id:

redis:
  enabled: true
  port: "{{ .Values.app.phraseanet_cache_port }}"

http:
  max_body_size: 2G
  max_input_vars: 12000
  gateway_allowed_ips:
  gateway_denied_ips:
  gateway_users:
  gateway_https: "on"
  gateway_csp: "default-src 'self' 127.0.0.1 https://apiws.carrick-skills.com:8443 https://apiws.carrick-flow.com:8443 https://fonts.gstatic.com *.tiles.mapbox.com https://api.mapbox.com https://events.mapbox.com *.axept.io *.matomo.cloud *.newrelic.com *.nr-data.net https://www.googletagmanager.com *.google-analytics.com *.phrasea.io https://apiws.carrick-flow.com:8443 https://apiws.carrick-skills.com:8443 data: ;script-src 'unsafe-inline' 'unsafe-eval' 'self' https://www.gstatic.com *.alchemyasp.com *.axept.io *.matomo.cloud *.newrelic.com https://www.googletagmanager.com https://apiws.carrick-flow.com:8443 https://apiws.carrick-skills.com:8443 ;style-src 'self' 'unsafe-inline' https://fonts.gstatic.com https://fonts.googleapis.com https://www.google.com https://www.gstatic.com https://apiws.carrick-flow.com:8443 https://apiws.carrick-skills.com:8443;img-src 'self' data: blob: *.tiles.mapbox.com https://axeptio.imgix.net *.cloudfront.net *.phrasea.io *.amazonaws.com https://apiws.carrick-flow.com:8443 https://apiws.carrick-skills.com:8443 ; object-src 'self';frame-ancestors 'self'"
  request_limits: false
  read_request_limit_memory: 10
  read_request_limit_rate: 100
  read_request_limit_burst: 20
  write_request_limit_memory: 10
  write_request_limit_rate: 100
  write_request_limit_burst: 20

php:
  php_cli_memory_limit: "2048M"
  fpm_memory_limit: "2048M"
  php_upload_tmp_dir: "/var/alchemy/Phraseanet/tmp/php_upload_tmp"
  fpm_pm_type: "dynamic"
  fpm_maxchildren: 9
  fpm_startservers: 3
  fpm_minspareserver: 2 
  fpm_maxspareserver: 4
  fpm_max_requests: 1000
  newrelic_enabled: false
  newrelic_licence_key:
  newrelic_app_name:
  opcache_enabled: 1
  log_level: warning
  session_cache_limiter: off
  session_save_handler: redis
  session_save_path: "tcp://redis-session:6379"
  cookie_secure: 0

ingress:
  enabled: true
  host: phraseanet
  tls: false

saml:
  enabled: false
  annotations: {}
  phraseanet_k8s_namespace:
  saml_phraseanet_host:
  saml_sp_authsources:
  saml_configmap:
    enabled: false
    idp_config:
    authsources_config:
  saml_secrets:
    enabled: false
    all:
      #phrasea.pem: ''
      #phrasea.crt: ''
  pvc:
    idp:
      name: phraseanet-saml-idp
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    sp:
      name: phraseanet-saml-sp
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    cert:
      name: phraseanet-saml-cert
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi

app:
  env_set_phraseanet_project_name: 1
  phraseanet_project_name: My Phraseanet
  phraseanet_hostname: localhost
  phraseanet_scheme: http
  phraseanet_install: 1
  phraseanet_setup: 1
  phraseanet_upgrade: 1
  phraseanet_admin_account_id:
  phraseanet_admin_account_email: admin@alchemy.fr
  phraseanet_admin_account_password: phraseanet
  phraseanet_db_host: mam-sandbox.cifgalpx8ots.us-west-2.rds.amazonaws.com
  phraseanet_db_port: 3306
  phraseanet_db_user: root
  phraseanet_db_password: phraseanet
  phraseanet_cache_type: redis
  phraseanet_cache_host: redis
  phraseanet_cache_port: 6379
  phraseanet_cache_domain: phraseanet
  phraseanet_elasticsearch_host: elasticsearch
  phraseanet_elasticsearch_port: 9200
  phraseanet_rabbitmq_host: rabbitmq
  phraseanet_rabbitmq_port: 5671
  phraseanet_rabbitmq_ssl: true
  phraseanet_rabbitmq_vhost: /
  phraseanet_rabbitmq_user: rabbit
  phraseanet_rabbitmq_pass: rabbitrabbit
  phraseanet_session_type: redis
  phraseanet_session_host: redis-session
  phraseanet_session_port: 6379
  phraseanet_user_session_idle: 14400
  phraseanet_user_session_lifetime: 86400
  phraseanet_available_language: fr,en,de,du
  phraseanet_default_language: en
  phraseanet_api_enabled: 1
  phraseanet_api_ssl: true
  phraseanet_api_auth_token_header_only: false
  phraseanet_download_async: false
  phraseanet_emiter_email:
  phraseanet_mail_object_prefix: Phraseanet
  phraseanet_smtp_enabled:
  phraseanet_smtp_auth_enabled:
  phraseanet_smtp_secure_mode:
  phraseanet_smtp_host:
  phraseanet_smtp_port:
  phraseanet_smtp_user:
  phraseanet_smtp_password:
  phraseanet_emitter_email:
  phraseanet_mail_object_prefix:
  phraseanet_ffmpeg_timeout:
  phraseanet_ffprobe_timeout:
  phraseanet_gs_timeout:
  phraseanet_mp4box_timeout:
  phraseanet_swftools_timeout:
  phraseanet_unocon_timeout:
  phraseanet_exiftool_timeout:
  install_db_template: DublinCore
  install_appbox: ab_master
  install_databox: db_databox1
  phraseanet_trusted_proxies:
  phraseanet_maintenance: 0
  phraseanet_maintenance_message:
  imagemagick_policy_version: 7
  imagemagick_policy_width: 48KP
  imagemagick_policy_height: 48KP
  imagemagick_policy_map: 2048MiB
  imagemagick_policy_memory: 2048MiB
  imagemagick_policy_area: 4096MB
  imagemagick_policy_disk: 6GiB
  imagemagick_policy_temporary_path: /tmp
  gateway:
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
  web:
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
  worker:
    phraseanet_explode_worker: 1
    phraseanet_workers_launch_method:
    phraseanet_worker_mainqueue: 3
    phraseanet_worker_assetsingest: 1
    phraseanet_worker_createrecord: 2
    phraseanet_worker_deleterecord: 2
    phraseanet_worker_editrecord: 2
    phraseanet_worker_exportmail: 2
    phraseanet_worker_downloadasync: 2
    phraseanet_worker_exposeupload: 2
    phraseanet_worker_ftp: 1
    phraseanet_worker_populateindex: 1
    phraseanet_worker_pullassets: 1
    phraseanet_worker_recordsactions: 1
    phraseanet_worker_subdefcreation: 1
    phraseanet_worker_subtitle: 1
    phraseanet_worker_validationreminder: 1
    phraseanet_worker_webhook: 1
    phraseanet_worker_writemetadatas: 1
    phraseanet_worker_sharebasket: 1
    phraseanet_cmd_mode: 1
    phraseanet_scheduler: 1
    launch:
      monoworker: true
      records: false
      subdefcreation: false
      writemetadatas: false
      exportemail: false
      exportftp: false
      ps: false
      noscalable: false
      cmd: false
      scheduler: false
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
  cronjobs:
  - id: job-1
    installed: true
    name: validationreminder
    suspend: false
    schedule: "0 0-23/2 * * *"
    command: "bin/console validation:remind"
  - id: job-2
    installed: false
    name: cleanusers
    suspend: true
    schedule: "30 3 * * 2"
    command: "bin/maintenance clean:user --inactivity_period 365 --grace_duration 7 --max_relances 2 --remove_basket --dry-run"
  - id: job-3
    installed: false
    name: apilogclean
    suspend: false
    schedule: "* 5 * * 5"
    command: "bin/maintenance clean:ApiLogs --help"
  - id: job-4
    installed: false
    name: workerjobclean
    suspend: false
    schedule: "* 4 * * 3"
    command: "bin/maintenance clean:WorkerRunningJob --help"
  - id: job-5
    installed: false
    name: dbbackup
    suspend: false
    schedule: "* 5 * * 0-6"
    command: "bin/console system:backup-db -g backup/"
  replicas:
    fpm:
      scale: 1
    gateway:
      scale: 1
    subdefcreation:
      scale: 1
    records:
      scale: 1
    exportemail:
      scale: 1
    exportftp:
      scale: 1
    ps:
      scale: 1
    writemetadatas:
      scale: 1
    monoworker:
      scale: 1
    cmd:
      scale: 1
  hpa:
    fpm:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      cpuAverageUtilization: 2000
    gateway:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      cpuAverageUtilization: 250
    subdefcreation:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      cpuAverageUtilization: 1000
    records:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      cpuAverageUtilization: 250
    exportemail:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      cpuAverageUtilization: 250
    ps:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      cpuAverageUtilization: 250
    writemetadatas:
      enabled: false
      minReplicas: 1
      maxReplicas: 1
      cpuAverageUtilization: 2000
    exportftp:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      cpuAverageUtilization: 1000
  pvc:
    data:
      name: phraseanet-datas
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    thumbnails:
      name: phraseanet-thumbnails
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    custom:
      name: phraseanet-custom
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    config:
      name: phraseanet-config
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    wwwplugins:
      name: phraseanet-wwwplugins
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    tmp:
      name: phraseanet-tmp
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    ftp:
      name: phraseanet-ftp
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    backup:
      name: phraseanet-backup
      persistence:
        enabled: true
        existingClaim:
        storageClass: standard
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
  persistence:
    enabled: true
    existingClaim:
    storageClass: standard
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 1Gi
  pvc_name:
      data: phraseanet-datas
      thumbnails: phraseanet-thumbnails
      custom: phraseanet-custom
      config: phraseanet-config
      ftp: phraseanet-ftp
      backup: phraseanet-backup
